"""initial schema

Revision ID: bd07445ce82c
Revises: 
Create Date: 2026-05-16 00:12:51.044406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd07445ce82c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('component_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_footprint', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('component_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('supplier_name')
    )
    op.create_table('materials',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('component_id', sa.String(length=36), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('blocks',
    sa.Column('block_id', sa.String(length=36), nullable=False),
    sa.Column('block_name', sa.String(length=255), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('co2e_value', sa.Integer(), nullable=False),
    sa.Column('supplier_reported_co2e_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocks')
    op.drop_table('materials')
    op.drop_table('suppliers')
    op.drop_table('components')
    # ### end Alembic commands ###
